ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "msSubscriptionId" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'MANUAL';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "msEventId" TEXT;
